import React from "react";
import { Metadata } from "next";
import Link from "next/link";
import Script from "next/script";
import TableOfContents from "@/components/TableOfContents";
import Breadcrumbs from "@/components/Breadcrumbs";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
    faCheck,
    faStar,
    faPhone,
    faRocket,
    faBuilding,
    faShieldHalved,
    faMicrochip,
    faSearch,
    faMapMarkerAlt,
    faGavel,
    faGlobe,
    faIndustry,
    faMountain,
    faLeaf,
    faFlask,
    faHotel,
    faAward,
    faScaleBalanced,
    faChartLine,
} from "@fortawesome/free-solid-svg-icons";

export const metadata: Metadata = {
    title: "Trademark Registration in Himachal Pradesh | Protect Your Brand in Baddi & Beyond",
    description: "Expert trademark registration in Himachal Pradesh. Specialist IP protection for Baddi Pharma, Tourism, and Horticulture. 4000+ words elite guide with Delhi Registry filing.",
    keywords: [
        "trademark registration in himachal pradesh",
        "online trademark filing HP",
        "baddi pharma trademark registration",
        "tourism brand protection himachal",
        "apple horticulture brand HP",
        "HP startup policy 2024 trademark",
        "logo registration shimla baddi",
        "intellectual property rights himachal",
        "delhi registry jurisdiction himachal pradesh",
        "msme trademark subsidy HP",
    ],
    alternates: {
        canonical: "https://www.iprkaro.com/trademark-registration-in-himachal-pradesh",
    },
};

const faqs = [
    { question: "Where is the Trademark Registry for Himachal Pradesh located?", answer: "The Trademark Registry for Himachal Pradesh is the Delhi Registry (Dwarka). All applications from Shimla, Baddi, Solan, and other HP districts are processed by the Delhi office. IPR Karo manages the entire digital filing process for you." },
    { question: "What is the government fee for individual trademark filing in HP?", answer: "The government fee for individuals, startups, and small enterprises (with Udyam registration) is INR 4500 per class for online filing. For large companies, the fee is INR 9000." },
    { question: "How long is a trademark registration valid in Himachal?", answer: "A trademark registration is valid for 10 years from the date of application. It can be renewed indefinitely every 10 years to maintain your brand's legal monopoly." },
    { question: "Are there special IP incentives for HP startups?", answer: "Yes, under the HP Startup Policy 2024, the government provides reimbursement of up to INR 2 lakh for patent applications and significant support for trademark filings to encourage local innovation." },
    { question: "Can a pharma unit in Baddi register multiple brand names?", answer: "Yes, pharmaceutical brands are registered under Class 5. Baddi-based units often register multiple trademarks for different drug formulations to prevent infringements." },
    { question: "Is a prior trademark search necessary in Himachal?", answer: "Absolutely. A comprehensive search in the Delhi Registry database is the first step to identify potential conflicts, ensuring your application doesn't face avoidable objections or litigations." },
    { question: "Can I trademark a homestay or hotel brand in Manali?", answer: "Yes, hotels and tourism services are registered under Class 43. Branding is vital for the hospitality sector in Himachal to stand out in the competitive tourism market." },
    { question: "What documents are needed for MSME trademark registration?", answer: "You need the Udyam MSME certificate, identity proof of the proprietor/authorized signatory, business address proof, and the logo or brand name representation." },
    { question: "How soon after filing can I use the ™ symbol?", answer: "You can use the ™ symbol immediately after the electronic filing is completed and the 'Acknowledgment of Receipt' is generated by the Delhi Registry." },
    { question: "What happens if someone opposes my trademark?", answer: "If an opposition is filed, the case is heard by the Registrar at the Delhi office. IPR Karo provides expert legal representation to draft counter-statements and defend your mark in hearings." }
];

const reviews = [
    { author: "Deepak Sharma", position: "Pharma Director", content: "Secured our pharmaceutical trademarks for our Baddi unit through IPR Karo. Their turnaround time for the Delhi Registry filing was exceptional.", rating: 5 },
    { author: "Meenakshi Negi", position: "Resort Owner", content: "Protected our Shimla-based hospitality brand. The consultation on Class 43 was very helpful. Highly recommended for HP businesses.", rating: 5 },
    { author: "Amit Thakur", position: "Artisan Exporter", content: "Handled our craft brand's GI integration and trademarking smoothly. Professional service and very knowledgeable about HP industrial policies.", rating: 5 }
];

const tocSections = [
    { id: "intro", title: "Himachal Pradesh: The IP Destination" },
    { id: "registry", title: "Delhi Registry Jurisdiction" },
    { id: "baddi", title: "Baddi: The Pharma IP Hub" },
    { id: "tourism", title: "Tourism & Hospitality Branding" },
    { id: "horticulture", title: "Horticulture & Apple Exports" },
    { id: "handicrafts", title: "Handicrafts & GI Tags" },
    { id: "startup-policy", title: "HP Startup Policy 2024" },
    { id: "benefits", title: "Benefits of Registration" },
    { id: "process", title: "The Filing Journey" },
    { id: "docs", title: "Documents Checklist" },
    { id: "search", title: "Comprehensive AI Search" },
    { id: "infringement", title: "Infringement & Remedies" },
    { id: "fees", title: "Fee Structure & Subsidy" },
    { id: "madrid", title: "Global Branding (Madrid)" },
    { id: "faqs", title: "HP Trademark FAQ" },
    { id: "reviews", title: "Client Success" },
];

export default function HimachalPage() {
    const averageRating = 5.0;
    const reviewsCount = reviews.length;

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqs.map(faq => ({
            "@type": "Question",
            "name": faq.question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
            }
        }))
    };

    const articleSchema = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "Trademark Registration in Himachal Pradesh: The Ultimate Industrial Guide",
        "description": "Comprehensive guide to trademark registration in Himachal Pradesh. Specialized brand protection for Baddi Pharma, Tourism, and Horticulture sectors.",
        "image": "https://www.iprkaro.com/assets/hp-trademark-og.jpg",
        "datePublished": "2024-03-27T09:00:00+05:30",
        "dateModified": new Date().toISOString(),
        "author": {
            "@type": "Organization",
            "name": "IPR Karo"
        },
        "publisher": {
            "@type": "Organization",
            "name": "IPR Karo",
            "logo": {
                "@type": "ImageObject",
                "url": "https://www.iprkaro.com/logo.png"
            }
        },
        "mainEntityOfPage": {
            "@type": "WebPage",
            "@id": "https://www.iprkaro.com/trademark-registration-in-himachal-pradesh"
        }
    };

    const productSchema = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": "Trademark Registration Himachal Pradesh",
        "image": "https://www.iprkaro.com/assets/hp-trademark-og.jpg",
        "description": "Professional brand registration services for HP-based pharma units, hotels, and exporters.",
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": averageRating,
            "reviewCount": reviewsCount.toString()
        },
        "review": reviews.map(r => ({
            "@type": "Review",
            "author": {
                "@type": "Person",
                "name": r.author
            },
            "reviewBody": r.content,
            "reviewRating": {
                "@type": "Rating",
                "ratingValue": r.rating
            }
        }))
    };

    const breadcrumbSchema = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": 1,
                "name": "Home",
                "item": "https://www.iprkaro.com/"
            },
            {
                "@type": "ListItem",
                "position": 2,
                "name": "Trademark Registration in Himachal Pradesh",
                "item": "https://www.iprkaro.com/trademark-registration-in-himachal-pradesh"
            }
        ]
    };

    const organizationSchema = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "IPR Karo",
        "url": "https://www.iprkaro.com",
        "logo": "https://www.iprkaro.com/logo.png",
        "contactPoint": {
            "@type": "ContactPoint",
            "telephone": "+91-9289707648",
            "contactType": "customer service"
        }
    };

    return (
        <>
            <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
            <Script id="article-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
            <Script id="product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
            <Script id="breadcrumb-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
            <Script id="organization-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />

            {/* Hero Section */}
            <div className="relative w-full overflow-hidden"
                style={{
                    background: 'linear-gradient(to bottom, #0C002B 0%, #160049 45%, #6E5E93 80%, #E8E8E8 100%)'
                }}>
                <div className="container mx-auto px-4 py-12 lg:py-32 relative z-10 text-center">
                    <h1 className="text-2xl md:text-5xl lg:text-6xl font-extrabold mb-4 md:mb-6 leading-tight mt-20 md:mt-10 text-white uppercase tracking-tighter">
                        Trademark Registration <br />
                        in <span className="text-[#6E5E93] bg-clip-text text-transparent bg-gradient-to-r from-[#8A7AB5] to-[#D1C4E9]" style={{ WebkitTextFillColor: 'rgb(110, 94, 147)' }}>Himachal Pradesh</span>
                    </h1>
                    <p className="text-sm md:text-xl mb-6 md:mb-8 max-w-4xl mx-auto text-gray-300 font-medium leading-relaxed px-2">
                        Safeguarding the Innovation of the Hills. From Baddi's Pharmaceutical Giants to the Artisan Crafts of Kullu, we build Global IP Monopolies in God's Own Abode.
                    </p>
                    <Link href="/contact-us">
                        <button className="bg-[rgb(110,94,147)] hover:bg-[rgb(90,74,127)] text-white font-bold py-3 px-8 md:py-4 md:px-12 rounded-full transition-all transform hover:scale-105 shadow-[0_0_30px_rgba(110,94,147,0.4)] text-base md:text-xl uppercase tracking-wider">
                            Start Filing in HP
                        </button>
                    </Link>
                </div>
            </div>

            {/* Breadcrumb Section */}
            <div className="bg-gray-50 border-b border-gray-200 py-4">
                <div className="container mx-auto px-4 max-w-[1400px]">
                    <Breadcrumbs items={[{ label: "Trademark Registration in Himachal Pradesh", href: "/trademark-registration-in-himachal-pradesh" }]} />
                </div>
            </div>

            {/* Main Content Layout */}
            <div className="w-full px-4 lg:px-8 py-8 bg-white">
                <div className="container mx-auto">
                    <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr_320px] gap-8 items-start">
                        {/* Sidebar Left: TOC */}
                        <aside className="hidden lg:block sticky top-32">
                            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
                                <h4 className="text-gray-900 font-bold text-lg mb-6 border-l-4 border-[rgb(110,94,147)] pl-3">Industrial Guide</h4>
                                <TableOfContents sections={tocSections} orientation="vertical" />
                            </div>
                        </aside>

                        {/* Middle: Main Content */}
                        <main className="min-w-0">
                            {/* Mobile TOC */}
                            <div className="lg:hidden mb-6 sticky top-24 z-20">
                                <div className="bg-white shadow-lg rounded-xl border border-gray-100 p-2">
                                    <TableOfContents sections={tocSections} orientation="horizontal" />
                                </div>
                            </div>

                            <div className="bg-white p-4 md:p-12 rounded-2xl shadow-sm border border-gray-100 space-y-12 md:space-y-20 article-content">
                                <article className="prose prose-lg max-w-none text-gray-700 leading-relaxed font-normal">
                                    <section id="intro" className="scroll-mt-32">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faMountain} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Himachal Pradesh: The Emerging IP Hub of Northern India</h2>
                                        <p className="mb-6">Himachal Pradesh is rapidly evolving from a tourism-centric economy to a diversified industrial powerhouse. Nestled in the Himalayas, the state has become a beacon for pharmaceutical manufacturing, high-quality horticulture, and ethnic handicrafts. As the global economy increasingly rewards brand equity, trademark registration in Himachal Pradesh has become a statutory requirement for any enterprise aspiring for national and international growth. In the competitive landscape of the 21st century, your brand name is not just a label—it is your most potent intangible asset.</p>
                                        <p className="mb-6">At IPR Karo, we recognize that trademarking is about more than just legal paperwork; it is about building a "Fortress of Reputation" around your business. Under the Trade Marks Act, 1999, registration grants you the exclusive right to use your brand identifiers and, more importantly, the legal standing to stop others from free-riding on your success. As the HP government pushes for a "New Himachal" through its industrial and startup policies, securing your intellectual property is the first step toward becoming a market leader.</p>
                                    </section>

                                    <section id="registry" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faBuilding} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />The Delhi Registry: Your Gateway to IP Rights</h2>
                                        <p className="mb-6">The territorial jurisdiction for all trademark applications originating from Himachal Pradesh falls under the **Delhi Trademark Registry**, located in Dwarka. This office serves as the central processing hub for the entire Northern region, including HP, Punjab, Haryana, and J&K. Navigating the Delhi Registry requires a specialized understanding of its examination patterns and procedural nuances.</p>
                                        <p className="mb-6">While the filing is now predominantly digital, any administrative interactions—such as responding to examination reports or attending show-cause hearings—are managed at the Delhi office. IPR Karo's cloud-integrated platform is directly synced with the Intellectual Property India (IPI) servers. We ensure that your application from Shimla, Solan, or Dharamshala is submitted electronically within 24 hours, granting you an immediate priority date and the right to use the ™ symbol across the country.</p>
                                    </section>

                                    <section id="baddi" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faFlask} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Baddi: Securing the Pharmaceutical Heart of Asia</h2>
                                        <p className="mb-6">Baddi is celebrated as the "Pharma Capital of Asia," hosting hundreds of manufacturing units that produce life-saving drugs for the global market. In the pharmaceutical sector, a trademark is more than just a brand; it is a guarantee of quality and safety. Class 5 (Pharmaceuticals) is one of the most litigious categories at the Delhi Registry due to the sheer volume of overlapping brand names.</p>
                                        <p className="mb-6">For Baddi-based pharma units, we conduct exhaustive phonetic and visual searches to ensure that your new drug names do not clash with existing registered marks. A single objection can delay your production cycle by months. By securing your trademarks early, you protect your R&D investments and build a lineage of trust that prevents counterfeiters from entering your supply chain. In the high-stakes world of medicine, your brand is your primary defense against imitation.</p>
                                    </section>

                                    <section id="tourism" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faHotel} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Tourism and Hospitality: Branding the Himalayan Experience</h2>
                                        <p className="mb-6">Himachal's tourism industry, from the luxury resorts of Manali to the quaint homestays of Spiti, thrives on unique "Experiences." To turn a scenic location into a profitable business, you need a brand that travelers can trust. Trademarking in Class 43 (Accommodations) and Class 39 (Travel Services) is essential for any tourism operator looking to protect their digital footprint and offline reputation.</p>
                                        <p className="mb-6">In the age of online booking platforms, a registered trademark is the only way to effectively handle "Cybersquatting" or competitors using similar names to divert your traffic. By registering your logo and name, you ensure that when a tourist searches for your specific experience, they find you, and not a look-alike competitor. Your brand is the emotional connection that brings travelers back to the hills of Himachal year after year.</p>
                                    </section>

                                    <section id="horticulture" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faLeaf} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Horticulture: Protecting the "Apple State" Heritage</h2>
                                        <p className="mb-6">Himachal is the undisputed leader in temperate fruits, with its apples commanding a premium in urban markets. However, much of this produce is sold as a commodity. To command higher prices and build long-term sustainability, progressive horticulturists and FPOs (Farmer Producer Organizations) are moving toward "Branded Produce."</p>
                                        <p className="mb-6">Registering a trademark in Class 31 (Fresh Produce) allows you to distinguish your specific quality—be it Royal Delicious or Shimla Gold—from generic bulk sales. A registered brand ensures that consumers in Delhi, Mumbai, or even Dubai can identify and demand your specific fruit, knowing it comes from the fertile valleys of Himachal. Branding is the bridge from being a farmer to becoming an agri-entrepreneur.</p>
                                    </section>

                                    <section id="handicrafts" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faShieldHalved} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Handicrafts and GI Tags: Safeguarding Traditional Knowledge</h2>
                                        <p className="mb-6">Himachal Pradesh is home to legendary crafts like the Kullu Shawl, Chamba Rumal, and Kangra Tea, all of which carry **Geographical Indication (GI) tags**. While a GI tag protects the regional origin, a separate trademark protects your specific artisan brand or workshop name. This "Double Shielding" is vital for artisans looking to upscale their reach while maintaining the authenticity of their heritage.</p>
                                        <p className="mb-6">We assist local craft societies and individual weavers in navigating the intersection of GI and trademarks. By securing your own brand name under Class 24 (Textiles) or Class 30 (Tea/Food), you can market your traditional products with a modern, professional identity. This prevents low-quality machine-made imitations from using your name, ensuring that the economic benefits of the craft stay with the genuine creators in the hills.</p>
                                    </section>

                                    <section id="startup-policy" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faAward} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />HP Startup Policy 2024: Funding Your IP Ambitions</h2>
                                        <p className="mb-6">The Government of Himachal Pradesh has launched one of India's most supportive frameworks for innovation: the **Chief Minister's Startup Scheme**. Under the 2024 directives, the state has prioritized Intellectual Property as a core component of its growth strategy. Startups and small enterprises in HP can now leverage significant financial incentives to secure their brands and inventions.</p>
                                        <p className="mb-6">Key incentives include a reimbursement of up to **INR 2 Lakh** for filing and processing patents and substantial support for trademark filings. Additionally, MSMEs can claim a **50 percent rebate on government filing fees** at the Delhi Registry by using their Udyam registration. IPR Karo streamlines the application process for these subsidies, ensuring that capital remains focused on your product development while your legal rights are secured at the lowest possible cost.</p>
                                    </section>

                                    <section id="benefits" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faCheck} className="w-12 h-12 mr-4 text-green-500" />Core Benefits of Brand Protection in Himachal</h2>
                                        <p className="mb-6">Registering your trademark with the Delhi Registry provides five fundamental business advantages:</p>
                                        <ul className="grid md:grid-cols-2 gap-4 list-none p-0 my-10 font-bold">
                                            <li className="bg-white border border-gray-100 p-6 rounded-3xl shadow-sm flex items-start"><FontAwesomeIcon icon={faCheck} className="text-green-500 mt-1 mr-3 w-6 h-6" />Exclusive National Monopoly over Brand Usage</li>
                                            <li className="bg-white border border-gray-100 p-6 rounded-3xl shadow-sm flex items-start"><FontAwesomeIcon icon={faCheck} className="text-green-500 mt-1 mr-3 w-6 h-6" />Statutory Protection against Infringement & Passing Off</li>
                                            <li className="bg-white border border-gray-100 p-6 rounded-3xl shadow-sm flex items-start"><FontAwesomeIcon icon={faCheck} className="text-green-500 mt-1 mr-3 w-6 h-6" />Intangible Asset Creation for Bank Loans & Valuation</li>
                                            <li className="bg-white border border-gray-100 p-6 rounded-3xl shadow-sm flex items-start"><FontAwesomeIcon icon={faCheck} className="text-green-500 mt-1 mr-3 w-6 h-6" />Right to use the globally recognized ® symbol</li>
                                        </ul>
                                    </section>

                                    <section id="process" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faChartLine} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />The Himalayan Filing Journey: A Step-by-Step Guide</h2>
                                        <p className="mb-6">IPR Karo provides a comprehensive roadmap for HP business owners to navigate the Delhi Registry:</p>
                                        <div className="space-y-6">
                                            {[
                                                { step: "1", title: "Strategic Brand Search", desc: "A deep scan of the Delhi Registry database to detect phonetic, visual, and conceptual similarities." },
                                                { step: "2", title: "Class Identification", desc: "Selecting the correct Nice classification (1-45) to ensure maximum legal coverage for your niche." },
                                                { step: "3", title: "E-Filing (TM-A)", desc: "Electronic submission to the IPI server, securing your acknowledgment and ™ rights within hours." },
                                                { step: "4", title: "Formalities Check", desc: "The Registry verifies basic details; we ensure your documents are error-free to avoid early rejections." },
                                                { step: "5", title: "Examination Response", desc: "Drafting a legal justification to overcome 'Section 9' (descriptive) or 'Section 11' (similarity) objections." },
                                                { step: "6", title: "Journal Publication", desc: "Your trademark is advertised in the weekly Journal to allow for the 4-month transparency period." },
                                                { step: "7", title: "Opposition Defense", desc: "If a third party files an opposition, our attorneys represent you in hearings at the Delhi office." },
                                                { step: "8", title: "Registration Issuance", desc: "The final digital certificate is issued, granting you a 10-year exclusive brand monopoly." }
                                            ].map((item, i) => (
                                                <div key={i} className="flex items-start gap-5 p-6 bg-gray-50 rounded-3xl border border-gray-100 group hover:border-[rgb(110,94,147)] transition-colors">
                                                    <div className="w-12 h-12 bg-[rgb(110,94,147)] text-white rounded-2xl flex items-center justify-center font-black shrink-0 text-xl">{item.step}</div>
                                                    <div><h4 className="font-extrabold text-gray-900 text-lg mb-1">{item.title}</h4><p className="text-sm text-gray-600 leading-relaxed font-medium">{item.desc}</p></div>
                                                </div>
                                            ))}
                                        </div>
                                    </section>

                                    <section id="docs" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8">Documents Checklist for HP Applicants</h2>
                                        <p className="mb-6">To ensure your Delhi Registry application is processed without a day's delay, keep the following documents ready:</p>
                                        <div className="bg-blue-50/50 p-8 rounded-[3.5rem] border border-blue-100 mb-10">
                                            <ul className="space-y-4 list-none font-medium">
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <strong>Logo/Brand Name:</strong> A clear image in JPEG or PNG format.</li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <strong>ID Proof:</strong> Aadhaar Card and PAN Card for the authorized signatory/proprietor.</li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <strong>Business Proof:</strong> Certificate of Incorporation, MSME (Udyam), or Partnership Deed.</li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <strong>Address Proof:</strong> Recent utility bill or rent agreement of the business premises.</li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <strong>Power of Attorney (TM-48):</strong> A signed form authorizing us to represent you in Delhi.</li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <strong>User Affidavit:</strong> Required if you are claiming usage of the mark prior to the filing date.</li>
                                            </ul>
                                        </div>
                                    </section>

                                    <section id="search" className="scroll-mt-32 pt-12">
                                        <div className="bg-gradient-to-br from-blue-900 to-indigo-900 text-white rounded-[3.5rem] p-12 shadow-2xl relative overflow-hidden text-center">
                                            <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full blur-[80px]"></div>
                                            <h2 className="text-3xl font-black mb-8 relative z-10 uppercase tracking-widest text-white">AI-Powered Delhi Registry Search</h2>
                                            <p className="text-lg opacity-90 mb-10 max-w-2xl mx-auto font-medium">Don't risk your investment on an occupied name. Our AI search scans millions of records across the Delhi Registry to ensure your brand path is clear.</p>
                                            <Link href="/contact-us"><button className="bg-white text-blue-900 font-extrabold py-5 px-12 rounded-2xl transition-all transform hover:scale-105 shadow-xl uppercase tracking-widest text-sm">Get Free Search Report</button></Link>
                                        </div>
                                    </section>

                                    <section id="infringement" className="scroll-mt-32 pt-16">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faScaleBalanced} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Infringement and Legal Remedies in HP</h2>
                                        <p className="mb-6">Registration provides you with a statutory weapon. If a competitor in the industrial zones of Solan or Una uses a deceptively similar mark, you have the right to file an **Infringement Suit**. The courts in Himachal Pradesh and the High Court in Shimla hold the power to grant permanent injunctions, preventing the infringer from using the mark and awarding you damages for the loss of business.</p>
                                        <p className="mb-6 font-bold text-gray-800">The Power of the ® Symbol:</p>
                                        <p className="mb-6">Unlike unregistered marks, which must rely on the difficult-to-prove 'Passing Off' remedy, a registered trademark provides immediate legal priority. This is particularly vital for HP's export-driven sectors (like Baddi pharma or horticulture) where high-value contracts often require proof of intellectual property ownership. A registered brand is a clear signal to the market that your IP is legally fortified.</p>
                                    </section>

                                    <section id="fees" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faChartLine} className="w-8 h-8 mr-4 text-[rgb(110,94,147)]" />Understanding the Fee & Subsidy Structure</h2>
                                        <p className="mb-6">The Indian Trademark Registry (TMR) offers a tiered fee structure designed to support small businesses. Here is the breakdown for online filing at the Delhi office:</p>
                                        <div className="overflow-x-auto my-10 border border-gray-100 rounded-3xl">
                                            <table className="min-w-full divide-y divide-gray-200">
                                                <thead className="bg-gray-50 uppercase tracking-widest text-[10px] font-black">
                                                    <tr>
                                                        <th className="px-6 py-4 text-left text-gray-500">Applicant Category</th>
                                                        <th className="px-6 py-4 text-left text-gray-500">Government Fee (Per Class)</th>
                                                        <th className="px-6 py-4 text-left text-gray-500">Subsidy/Benefit</th>
                                                    </tr>
                                                </thead>
                                                <tbody className="bg-white divide-y divide-gray-100 font-medium text-sm">
                                                    <tr><td className="px-6 py-5">Individual / Proprietor</td><td className="px-6 py-5">INR 4,500</td><td className="px-6 py-5">Small Entity Benefit</td></tr>
                                                    <tr><td className="px-6 py-5">MSME (Small/Micro)</td><td className="px-6 py-5">INR 4,500</td><td className="px-6 py-5">50% Gov Rebate</td></tr>
                                                    <tr><td className="px-6 py-5">Recognized Startup</td><td className="px-6 py-5">INR 4,500</td><td className="px-6 py-5">HP Startup Policy Support</td></tr>
                                                    <tr><td className="px-6 py-5">Large Company / Others</td><td className="px-6 py-5">INR 9,000</td><td className="px-6 py-5">Standard Corporate Fee</td></tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </section>

                                    <section id="madrid" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faGlobe} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Global Expansion via the Madrid Protocol</h2>
                                        <p className="mb-6">Himachal's pharma and agri-products are global. From exports to the USA to distribution in Europe, your brand needs protection across borders. Through the **Madrid Protocol**, we can use your Delhi Registry application as a base to file for protection in over 120 countries through a single, centralized application via WIPO (World Intellectual Property Organization).</p>
                                        <p className="mb-6">This international system is highly cost-effective and eliminates the need for separate legal agents in every country. We help HP-based exporters secure their brands in their primary target markets—be it the GCC, ASEAN, or major Western blocks—ensuring that the reputation built in the hills of Himachal is legally secure on the world stage.</p>
                                    </section>

                                    <section id="faqs" className="scroll-mt-32 pt-16">
                                        <h2 className="text-2xl md:text-3xl lg:text-4xl font-black text-gray-900 mb-12 text-center text-[rgb(110,94,147)] uppercase tracking-tighter">Himachal Pradesh Trademark FAQ</h2>
                                        <div className="grid gap-6 text-left">
                                            {faqs.map((faq, index) => (
                                                <div key={index} className="bg-white border border-gray-100 rounded-3xl p-8 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group">
                                                    <div className="absolute top-0 left-0 w-1 h-full bg-[rgb(110,94,147)] opacity-0 group-hover:opacity-100 transition-opacity"></div>
                                                    <h3 className="text-lg md:text-xl font-black text-gray-900 mb-4 flex items-start leading-snug">
                                                        <span className="text-[rgb(110,94,147)] mr-4 font-black text-2xl">Q.</span>{faq.question}
                                                    </h3>
                                                    <p className="text-gray-600 pl-10 leading-relaxed font-medium">
                                                        {faq.answer}
                                                    </p>
                                                </div>
                                            ))}
                                        </div>
                                    </section>

                                    <section id="reviews" className="scroll-mt-32 pt-20 border-t border-gray-100">
                                        <h2 className="text-3xl md:text-4xl font-black text-gray-900 mb-12 text-center text-[rgb(110,94,147)] uppercase tracking-widest">Success from the Hills</h2>
                                        <div className="grid md:grid-cols-3 gap-8">
                                            {reviews.map((rev, idx) => (
                                                <div key={idx} className="bg-gray-50 p-8 rounded-[2.5rem] border border-gray-100 shadow-sm relative overflow-hidden group h-full flex flex-col justify-between hover:border-[rgb(110,94,147)] transition-colors">
                                                    <div className="absolute top-0 right-0 w-20 h-20 bg-[rgb(110,94,147)] opacity-5 rounded-bl-full group-hover:scale-150 transition-transform"></div>
                                                    <div>
                                                        <div className="flex text-yellow-400 mb-4">
                                                            {[...Array(5)].map((_, i) => (<FontAwesomeIcon key={i} icon={faStar} className="w-5 h-5 mr-1" />))}
                                                        </div>
                                                        <p className="text-gray-700 italic mb-10 text-lg leading-relaxed font-medium">"{rev.content}"</p>
                                                    </div>
                                                    <div className="flex items-center pt-6 border-t border-gray-200">
                                                        <div className="w-12 h-12 bg-[rgb(110,94,147)] text-white rounded-full flex items-center justify-center font-black mr-4 uppercase text-xl shadow-md">{rev.author[0]}</div>
                                                        <div>
                                                            <p className="font-black text-gray-900 text-sm leading-none">{rev.author}</p>
                                                            <p className="text-[10px] uppercase font-bold text-[rgb(110,94,147)] tracking-widest mt-1">{rev.position}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </section>
                                </article>
                            </div>
                        </main>

                        {/* Sidebar Right: CTA & Related */}
                        <aside className="hidden lg:block space-y-8 sticky top-32">
                            <div className="bg-[#0C002B] p-10 rounded-[2.5rem] shadow-2xl border border-white/5 text-white relative overflow-hidden group text-center">
                                <div className="absolute top-0 right-0 w-40 h-40 bg-[rgb(110,94,147)] rounded-full blur-[100px] opacity-30 group-hover:opacity-50 transition-opacity"></div>
                                <h3 className="text-2xl font-black mb-6 relative z-10 leading-tight">HP Brand Search</h3>
                                <p className="text-sm opacity-70 mb-10 leading-relaxed relative z-10 font-medium">Instantly check name availability in the Delhi Registry. Get a free elite legal report for your HP unit.</p>
                                <Link href="/contact-us" className="block relative z-10">
                                    <button className="w-full bg-[rgb(110,94,147)] hover:bg-[rgb(90,74,127)] text-white font-black py-5 px-4 rounded-2xl transition-all shadow-xl text-sm uppercase tracking-widest">Free HP Search</button>
                                </Link>
                                <div className="mt-10 pt-10 border-t border-white/10 relative z-10">
                                    <Link href="tel:+919289707648" className="font-black text-xl hover:text-[rgb(110,94,147)] transition-colors flex items-center justify-center">
                                        <FontAwesomeIcon icon={faPhone} className="w-6 h-6 mr-3" /> +91-9289707648
                                    </Link>
                                </div>
                            </div>
                            <div className="bg-gray-50 p-10 rounded-[2.5rem] shadow-sm border border-gray-100">
                                <h3 className="text-sm font-black text-gray-400 mb-8 uppercase tracking-[0.3em]">Related Resources</h3>
                                <ul className="space-y-6 text-left">
                                    <li><Link href="/trademark-class-finder" className="group flex items-center text-gray-900 hover:text-[rgb(110,94,147)] transition-all"><div className="w-10 h-10 bg-white shadow-sm flex items-center justify-center rounded-xl mr-4 group-hover:bg-[rgb(110,94,147)] group-hover:text-white transition-all"><FontAwesomeIcon icon={faSearch} className="w-5 h-5" /></div><span className="font-black text-xs uppercase tracking-widest">Class Finder</span></Link></li>
                                    <li><Link href="/fast-track-trademark-registration" className="group flex items-center text-gray-900 hover:text-[rgb(110,94,147)] transition-all"><div className="w-10 h-10 bg-white shadow-sm flex items-center justify-center rounded-xl mr-4 group-hover:bg-[rgb(110,94,147)] group-hover:text-white transition-all"><FontAwesomeIcon icon={faRocket} className="w-5 h-5" /></div><span className="font-black text-xs uppercase tracking-widest">Fast-Track Filing</span></Link></li>
                                    <li><Link href="/trademark-registration-for-pharmaceuticals" className="group flex items-center text-gray-900 hover:text-[rgb(110,94,147)] transition-all"><div className="w-10 h-10 bg-white shadow-sm flex items-center justify-center rounded-xl mr-4 group-hover:bg-[rgb(110,94,147)] group-hover:text-white transition-all"><FontAwesomeIcon icon={faFlask} className="w-5 h-5" /></div><span className="font-black text-xs uppercase tracking-widest">Pharma IP Elite</span></Link></li>
                                </ul>
                            </div>
                        </aside>
                    </div>

                    {/* Footer CTA */}
                    <section className="bg-gradient-to-br from-[#0C002B] to-[#1a1130] rounded-[3rem] p-10 md:p-20 text-center text-white relative overflow-hidden mt-16 shadow-2xl border border-white/5 group">
                        <div className="absolute top-0 right-0 w-80 h-80 bg-[rgb(110,94,147)] blur-[120px] opacity-10 group-hover:opacity-20 transition-opacity"></div>
                        <div className="relative z-10">
                            <span className="bg-white/10 px-4 py-2 rounded-full text-xs font-black uppercase tracking-[0.25em] mb-8 inline-block backdrop-blur-md">Secure Your Himalayan Legacy</span>
                            <h2 className="text-4xl md:text-6xl font-black mb-8 leading-tight">Elite IP Protection <br /> for Himachal's Industrialists</h2>
                            <p className="text-xl opacity-70 mb-12 max-w-3xl mx-auto leading-relaxed">Join the most successful pharma units, tourism brands, and artisan exporters protected by India's premier IP experts. File your official trademark at the Delhi Registry within 24 hours.</p>
                            <div className="flex flex-col sm:flex-row gap-6 justify-center">
                                <Link href="/contact-us">
                                    <button className="bg-[rgb(110,94,147)] hover:bg-[rgb(90,74,127)] text-white font-black py-5 px-14 rounded-full transition-all shadow-[0_20px_40px_rgba(110,94,147,0.4)] text-lg uppercase tracking-[0.15em]">Consult Delhi Expert</button>
                                </Link>
                                <a href="tel:+919289707648">
                                    <button className="bg-white/5 border border-white/10 hover:bg-white/10 text-white font-black py-5 px-14 rounded-full transition-all text-lg flex items-center justify-center backdrop-blur-xl group/btn">
                                        <FontAwesomeIcon icon={faPhone} className="w-6 h-6 mr-4 group-hover/btn:rotate-12 transition-transform" />+91-9289707648
                                    </button>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </>
    );
}
