export const locations = [
  "Noida Sector 80", "Dilshad Garden Depot", "Yamuna Expressway Sector 25", "Noida City Center Metro", "Panna",
  "Indira Gandhi International Airport T1", "Sector 9 Vasundhara", "Gurugram HUDA City Center", "Janjgir-Champa", "Ballari",
  "Dwarka Mor Metro", "Noida Sector 146", "Surya Nagar", "Moradabad", "Shastri Nagar",
  "Uttam Nagar", "Rewa", "Ranchi", "Jhunjhunu", "Tuensang",
  "Crossing Republik Paramount Symphony", "Saiha", "Sarai Kale Khan ISBT", "Kozhikode", "AIIMS",
  "Sector Zeta 3", "Noida Sector 16A", "Okhla NSIC", "Hathras", "Abhay Khand 2",
  "Tughlaqabad", "Bastar", "Uttar Dinajpur", "Bagerhat", "East Siang",
  "Bageshwar", "Warangal (Rural)", "Dhule", "Warangal (Urban)", "Mount Gambier",
  "Narayanganj", "Mahe", "Raebareli", "Bangalore", "Faridabad Sector 10",
  "Nyay Khand 3", "Masuri", "Gurgaon", "Faridabad Sector 23", "Kavi Nagar",
  "Noida Extension Sector 20", "Kakinada", "Nabadwip", "Knowledge Park 4", "Faridabad", "Arunachal Pradesh", "Rangareddy", "Palamu", "Shalimar Garden Ext 2", "Naraina Vihar",
  "Nagpur", "Kushinagar", "Rajouri", "Jaipur", "Panaji", "Raipur", "Noida Sector 48", "Haridwar", "Malappuram", "Kanpur Nagar",
  "Connaught Place", "Tikamgarh", "Dhemaji", "Wardha", "Noida Sector 46", "Vaishali Sector 1", "Ramakrishna Ashram Marg", "Jamtara", "Nabarangpur", "Najafgarh Bus Stand",
  "Kannauj", "Yamunanagar", "Azadpur", "Cuddalore", "Theni", "Jama Masjid", "Sector Eta 1", "Greater Noida Sector Sigma 2", "Morbi", "Neemuch",
  "Noida Sector 142", "Firozpur", "Dharmapuri", "Supreme Court", "Lakshadweep", "Katihar", "Bhajarpura", "Gorakhpur", "Noida Extension Sector 12", "Rajouri Garden",
  "Sector 4 Vasundhara", "Karnataka", "Mandawali Fazalpur", "Muradnagar Main Market", "Loni Tronica City", "Shankar Vihar", "Rayagada", "Chandigarh", "Wave City Sector 1", "Greater Noida Sector Delta 2",
  "Niti Khand 3", "Govindpuram Extension", "Mahoba", "Gajapati", "Faridabad Sector 14", "Gautam Buddha Nagar", "Chhatarpur", "Gurugram Sector 5", "Vaishali Sector 7", "Chitrakoot",
  "Kalindi Kunj", "Raj Nagar Sector 7", "Thiruvallur", "Greater Noida Sector Zeta 2", "Greater Noida Sector Delta 3", "Haveri", "Sanjay Nagar Sector 1", "Raisen", "Dadra & Nagar Haveli", "Gurugram IFFCO Chowk",
  "Akshardham Temple", "Kendrapara", "Karol Bagh", "Bhojpur", "Noida Sector 18", "Pratapgarh", "Noida Sector 74", "Sector Omicron 1A", "Gurugram Sector 6", "Faridabad Sector 21A",
  "Andhra Pradesh", "West Godavari", "Banaras", "Rohini Sector 18", "Noida Sector 16", "Rahanpur", "Noida Sector 81", "Noida Sector 143A", "Preet Vihar Metro", "Sector 8 Vasundhara",
  "Tirap", "Fazilka", "Khanpur", "Jamnagar", "Gurugram Sector 4", "Karampura", "Dasna Village", "Chandigarh", "Govindpuram Sector 2", "Goalpara",
  "Thoubal", "Hamirpur", "Noida Sector 18", "Hoshiarpur", "Noida Sector 144", "Shastri Nagar Block B", "Tiruchirappalli", "Dindori", "Gurugram Sector 26", "AIIMS Metro",
  "Srinager", "Kanchipuram", "Shastri Nagar Block D", "Govindpuram Sector 8", "Dhamtari", "Khargone", "Ramgarh", "Noida Sector 71", "Gurugram Sector 9", "Sahibganj",
  "Kavi Nagar Sector 10", "Noida Sector 31", "Churu", "Greater Noida Sector Beta 2", "Vaishali Sector 4", "Dasna Industrial Area", "Mandi", "Faridabad Sector 31", "Noida Sector 149", "Upper Subansiri",
  "Gurugram Sector 22A", "Haridwar", "Poonch", "Sonbhadra", "Birbhum", "Meerut", "Noida Sector 134", "Madhya Pradesh", "Jaipur", "Khajuri Khas",
  "Dhanbad", "Jharsuguda", "Noida Sector 39", "Noida Sector 155", "Mizoram", "Gurgaon", "Varanasi", "Jehanabad", "Sector Zeta 4", "Rewari",
  "Patan", "Jodhpur", "Rohini Sector 24", "Dwarka Mor", "Noida Sector 12", "Gaya", "Vijayapura", "Noida Sector 60", "Sidhi", "Sant Ravidas Nagar",
  "Leh", "Mumbai City", "Adarsh Nagar", "Punjabi Bagh West", "Faridabad Sector 35", "Shahdara Depot", "Dumka", "Bhadradri Kothagudem", "Imphal", "Noida Sector 114",
  "Hindon Air Force Station", "Wave Executive Floors", "Wave City Sector 8", "Jatwara", "Mackay", "Mathura", "Sector 7 Vasundhara", "Koraput", "Faridabad Sector 17", "Muradnagar Industrial Area",
  "Surajpur", "Junagadh", "Nehru Place", "Punjabi Bagh Metro", "Pandav Nagar", "Noida Sector 100", "Noida Sector 28", "Shaheen Bagh", "Belagavi", "Narela",
  "Udaipur", "Crossing Republik Ajnara Gen X", "Railway Colony", "Una", "Gyan Khand 1", "Karampura Industrial Area", "Faridabad Sector 15", "Raigad", "Sector Xu 2", "Vaibhav Khand",
  "Crossings Republic Gaur Global Village", "Nalgonda", "Bhavnagar", "Noida Sector 21", "Purulia", "Karaikal", "Noida Sector 65", "Greater Noida Sector Omicron 2", "Doda", "Tronica City Sector D",
  "Panipat", "Gondia", "Mahbubabad", "Vasundhara Sector 1", "Gurugram Sector 35", "Gurugram Sector 31", "Indraprastha Park", "Noida Sector 37", "Greater Noida Sector Delta 4", "Vasant Kunj Bus Stand",
  "Siddharth Vihar Sector 4", "Nadia", "Purba Medinipur", "Indore", "Gurugram Sector 37C", "Noida Sector 6", "Jalandhar", "Niti Bagh Colony", "East Khasi Hills", "Panchkula",
  "Srikakulam", "Hooghly", "Seraikela-Kharsawan", "Yamuna Expressway Sector 24", "Bhopal", "Upper Siang", "Washim", "Rajdhani Park", "Sector Chi 3", "Kolkata",
  "West Champaran", "Andaman and Nicobar Islands", "Noida Sector 42", "Seemapuri", "Paharganj", "Udham Singh Nagar", "Nalbari", "Gurugram Sector 10A", "Ecotech 5", "Shakarpur",
  "Geraldton", "Faridabad Sector 11", "ITO", "Inderlok", "Hyderabad", "Nuapada", "Thiruvananthapuram", "Senapati", "Burari", "Noida Sector 122",
  "Brij Vihar", "Tilak Nagar", "Noida Sector 13", "Jajpur", "Kolar", "Gurugram Sector 7", "Gurugram Sector 37", "Alipurduar", "Banka", "Delhi University - North Campus",
  "Bhopal", "Shastri Nagar Block A", "Chhattarpur Temple", "Greater Noida Sector Omicron 1", "Noida Sector 15", "Kutch", "Greater Noida Sector Omicron 3", "Indirapuram Nyay Khand 3", "Sarita Vihar", "Bagalkote",
  "Nehrunagar Sector 3", "Dungarpur", "Ram Vihar", "Faridabad Sector 27", "Gir Somnath", "Shimoga", "Jamia Millia Islamia", "Noida Sector 38", "Karur", "Champhai",
  "Kavi Nagar Sector 13", "North Tripura", "Chhota Udepur", "Jaunpur", "Madhepura", "Vaishali Sector 6", "Jammu and Kashmir", "Medchal–Malkajgiri", "Tirunelveli", "Karimganj",
  "Wave City Sector 3", "Lower Subansiri", "Anjaw", "Noida Sector 23", "Gurugram Sector 25", "Gurugram Sector 10", "Noida Sector 59", "Tawang", "Delhi Cantonment Bus Terminal", "Bargarh",
  "Sivaganga", "Chamba", "Faridabad Sector 36", "Bhikaji Cama Place", "Vaishali Sector 5", "Ramprastha Colony", "Rajanna Sircilla", "Gurugram Sector 40", "Raj Nagar Sector 6", "Gorakhpur",
  "Modinagar Railway Station", "Mahipalpur", "Greater Noida Sector Tau 1", "Barabanki", "Kirbi Place", "Nehru Enclave", "Serchhip", "Perambalur", "Peren", "Red Fort (Lal Qila)",
  "IGI Airport Metro", "Kamareddy", "Namakkal", "Central Delhi", "Noida Sector 47", "Sanjay Nagar Sector 5", "Dhubri", "Fatehabad", "Sundargarh", "Deoria",
  "Munger", "Greater Noida Sector Gamma 1", "Noida Sector 93", "Tronica City Sector A", "Laxmi Nagar Bus Depot", "Bathinda", "Visakhapatnam", "Noida Sector 118", "Osmanabad", "Greater Noida Sector Zeta 1",
  "Noida Sector 57", "Noida Sector 139", "Belgaum", "Gurugram Sector 22B", "North East Delhi", "Faridabad Sector 22", "Hindon Residential Area", "Noida Sector 4", "Wave City Sector 7", "Lohardaga",
  "Vikaspuri", "Greater Noida Sector Alpha 1", "Kamrup Metropolitan", "Greater Noida Sector Sigma 4", "Mumbai", "Gurugram Sector 11", "Sindhudurg", "Basti", "Morti Extension", "Morena",
  "Bilaspur", "Noida Extension Sector 10", "Jaisalmer", "Gurugram Sector 38", "Narayanpur", "Firozabad", "Jabalpur", "Bengaluru Rural", "Thrissur", "Kalahandi",
  "Chitradurga", "Bareilly", "Mahasamund", "Shadipur Metro", "Sawai Madhopur", "Noida Sector 108", "Kochi", "Noida Sector 101", "Noida Sector 24", "Kolasib",
  "Vasundhara Sector 2", "Shadipur", "Pulwama", "Noida Sector 94", "Anand Vihar ISBT", "Leh", "Indirapuram Abhay Khand 1", "Yadgir", "Dhar", "Majnu Ka Tilla",
  "Tengnoupal", "Khagaria", "Jalaun", "Shahdara", "Noida Sector 2", "Gurugram Sector 2", "Kheri", "Simdega", "Koriya", "Gurugram Sector 34",
  "Okhla", "Uttarakhand", "Mohan Nagar Industrial Area", "Kottayam", "Jalpaiguri", "Murshidabad", "Sector Theta 3", "Dausa", "Kanpur", "Faridabad",
  "Noida Sector 148", "Howrah", "Kendujhar", "Malkangiri", "Siddipet", "Jorhat", "Noida Sector 15", "Shillong", "Gurugram Sector 9A", "Raj Nagar Sector 3",
  "Tiruvannamalai", "Naharlagun", "Gadchiroli", "Baramulla", "Patparganj", "Jasola Vihar", "Sonitpur", "Ballarat", "Hazaribagh", "North Garo Hills",
  "Mohan Estate", "Kingsway Camp", "Central Coast", "Sirmaur", "Kheda", "Barmer", "Guntur", "Sector 64 Indirapuram", "Faridabad Sector 33", "Krishna",
  "Hoshangabad", "North 24 Parganas", "Cuttack", "Parliament", "Najafgarh", "Etah", "Indirapuram Shakti Khand 1", "New Delhi", "Old Delhi Railway Station", "Mon",
  "Kurung Kumey", "Wollongong", "Ramprastha", "Kaushambi", "Mancherial", "Dibrugarh", "Datia", "Gujarat", "Gurugram Sector 24", "Sirohi",
  "Modinagar", "Raj Nagar", "Vasundhara Sector 9", "Aditya Park Town", "Arjangarh", "Noida Sector 45", "Noida Sector 120", "Noida Sector 85", "Imphal West", "Ballabhgarh",
  "Devbhoomi Dwarka", "Lunglei", "Sambalpur", "Bharat Nagar", "Ghaziabad Old Bus Stand", "Shalimar Bagh", "Gwalior", "Tiruppur", "Ecotech 7", "Noida Sector 135",
  "RK Puram", "Marigaon", "Sector 13 Vasundhara", "Thoubal", "Mehsana", "Najafgarh Depot", "Faridabad Sector 20", "Indirapuram", "Pali", "Balasore",
  "Noida Sector 76", "Faridkot", "Kashmere Gate ISBT", "Tirupati", "Moga", "Mayapuri", "Siddharth Vihar Sector 2", "Noida Sector 30", "Ghaziabad", "Raj Nagar Sector 5",
  "Hingoli", "Kaushambi", "Hyderabad", "Balia", "Sheohar", "Kalkaji Mandir", "Kavi Nagar Sector 12", "Bhadrak", "Mysuru", "Rohtas",
  "Kangra", "Noida Sector 126", "Noida Sector 12", "Noida Sector 136", "Noida Extension Sector 22D", "Tilak Nagar", "Vasant Kunj", "Faridabad Sector 16", "Victor Harbor–Goolwa", "Saran",
  "Bardhaman", "Wave City Sector 6", "Moti Nagar", "Rohini Sector 7", "Kanniyakumari", "Palam Metro", "Chhapraula", "Noida Sector 67", "Ramanagara", "Kinnaur",
  "Aurangabad", "Dwarka Sector 21", "Ecotech 6", "Vasundhara Sector 6", "Morti Village", "Geeta Colony", "Faizabad", "Noida Sector 5", "Sultanpur", "Gokalpuri",
  "Greater Noida Sector Tau 2", "Maharajganj", "Mohan Nagar Chowk", "Nagaland", "Fatepur", "Thiruvananthapuram", "Crossings Republic Flora", "Dholpur", "Faridabad Sector 24", "Noida Sector 130",
  "Hervey Bay", "Kamrup", "Dhubri", "Ahmedabad", "Noida Sector 52", "Yamuna Expressway Sector 27", "Gangtok", "Noida Extension Sector 16B", "Noida Sector 53", "Indirapuram Nyay Khand 1",
  "Defence Colony", "Thanjavur", "Ganderbal", "Pratap Vihar Sector 1", "Herat", "Lower Dibang Valley", "Anuppur", "Patparganj Metro", "Faridabad Sector 21C", "Meghalaya",
  "Faridabad Sector 28", "Noida Sector 41", "Gyan Khand 2", "Tronica City Sector C", "Shyam Park Main", "Noida Sector 50", "Jamshedpur", "Bhagalpur", "Noida Sector 133", "Sector 5 Vasundhara",
  "Sheikhpura", "Champawat", "Bahraich", "Kasaragod", "Singrauli", "Faridabad Sector 29", "Chikkamagaluru", "Noida Sector 82", "Newcastle–Maitland", "Siwan",
  "Yavatmal", "Udhampur", "Kalai", "Vasundhara Sector 11", "Bangalore Rural", "Garhwa", "Tronica City Industrial Area", "Nangloi", "Noida Sector 10", "Solan",
  "Noida Sector 104", "Noida Sector 123", "New Delhi", "Fayzabad", "Daryaganj", "Noida Extension Sector 16C", "Rajniwas Marg", "Udaipur", "Kanpur Dehat", "Dahod",
  "Wave City Sector 4", "Sector Xu 1", "Tapi", "Rithala", "Indirapuram Shakti Khand 4", "Sector Eta 3", "Chander Nagar", "Noida Sector 158", "Viluppuram", "Jirapur",
  "Dharwad", "Noida Sector 140", "Tinsukia", "East Godavari", "Bharat City Township", "Beed", "Crossing Republik Mahagun Mascot", "Mainpuri", "Rajendra Place", "Vasundhara Sector 5",
  "Amrapali Dream Valley", "Darrang", "Shalimar City", "Suryapet", "Noida Sector 90", "Indore", "Crossing Republik Galleria Market", "Banaskantha", "Dhaka", "Sector 14 Vasundhara",
  "Gurugram Sector 45", "East Garo Hills", "Ranchi", "Sector 62 Indirapuram", "South Tripura", "Mandawali Metro", "Kupwara", "Sector Xu 3", "Gariaband", "Noida Sector 32",
  "Idukki", "Chandel", "Kathua", "Noida Sector 147", "Mandsaur", "Meherpur", "Noida Extension Sector 2", "Noida Sector 111", "Dakshina Kannada", "Chennai",
  "Knowledge Park 3", "Indirapuram Abhay Khand 2", "Chamarajanagar", "Kalkaji Mandir Metro", "Ajnara Homes", "Phek", "Puducherry", "Daman", "Sant Nagar", "Ludhiana",
  "Mundka Industrial Area", "Noida Sector 141", "Geelong", "Yamuna Expressway Sector 26", "Wave City NH-24", "Noida Sector 11", "Kodagu", "Udaipur", "Techzone V", "Yamuna Expressway Sector 20",
  "Chhindwara", "Kaushambi GDA Flats", "Ramesh Nagar", "Faridabad Sector 2", "Vizianagaram", "Puri", "Madhubani", "Barisal", "Sri Ganganagar", "Noida Sector 110",
  "Mehrauli Bus Depot", "Kollam", "Howrah", "Bangalore Urban", "Kirti Nagar Industrial Area", "Tripura", "Dwarka Sector 21", "Sukma", "Tura", "Gadag",
  "Baghpat", "Raj Nagar Sector 1", "Begusarai", "Udalguri", "Bahadurgarh City", "Gurugram Sector 14", "Nirman Vihar Bus Stop", "West Kameng", "Khordha", "Mukherjee Nagar",
  "Kanyakumari", "Davanagere", "Tarntaran", "Pushp Vihar", "Karbi Anglong", "Bankura", "Noida Sector 49", "Bulandshahr", "Noida Sector 62", "Noida Extension Sector 16",
  "Indirapuram Shakti Khand 2", "Jammu", "Indirapuram Abhay Khand 3", "Khammam", "GT Karnal Road", "Bihar", "Seelampur", "Sector Eta 2", "Narsinghpur", "Ujjain",
  "Civil Lines", "South East Delhi", "Noida Sector 51", "Botad", "Ecotech 2", "Shahjahanpur", "Jhansi", "Papum Pare", "Tonkolili", "Namchi",
  "Modinagar Delhi-Meerut Road", "Rajendra Nagar", "Greater Noida Sector Sigma 1", "Narayana Vihar", "Faridabad Sector 1", "Rupnagar", "Alamdanga", "Kavi Nagar Sector 11", "Kurukshetra", "Sanjay Nagar Sector 6",
  "Wave City Sector 5", "Tagore Garden", "Sitamarhi", "Noida Sector 117", "Sangareddy", "Warangal", "Rani Jhansi Road", "Noida Sector 36", "Sector Omicron 4", "Govindpuram Sector 7",
  "Jhilmil Industrial Area", "Karnal", "Welcome Metro Station", "Vasundhara Sector 7", "West Tripura", "Rajokri", "Seoni", "Sector Phi 2", "Lucknow", "Ramprastha Greens",
  "Noida Sector 38A", "Botanical Garden Metro", "Jharkhand", "Ghitorni", "Sikkim", "Shyam Park Extension", "Chittoor", "Churachandpur", "Mayur Vihar Phase III", "Batla House",
  "Noida Sector 160", "Lajpat Nagar", "Nandgram", "Wazirabad", "Udupi", "Shravasti", "Noida Sector 29", "Mandla", "Raj Nagar Sector 2", "Noida Sector 73",
  "Goa", "Tamenglong", "Jhajjar", "Ashok Vihar", "Dasna NH-24", "Mahabubnagar", "Anantapur", "Noida Sector 34", "Pragati Maidan", "North West Delhi",
  "Aizawl", "Faridabad Sector 15A", "Navsari", "Chengalpattu", "Sitapur", "Kalyanpuri Metro", "Ghaziabad", "Pratap Vihar Sector 2", "Gulbarga", "Bharatpur",
  "Surendranagar", "Pondicherry", "Ecotech Extension", "Noida Sector 72", "South West Delhi", "Sheopur", "Noida Sector 159", "Noida Sector 14", "Raj Nagar Extension", "Rohini Sector 11",
  "Krishnagiri", "Karkardooma", "Kapasheda Border", "Kovilpatti", "Gurugram Sector 17", "Tronica City Sector E", "Odisha", "Vidhan Sabha", "Noida Sector 124", "Sector Zeta 5",
  "Vaishali Sector 2", "Vaishali Metro", "Ramban", "East Singhbhum", "Erode", "Techzone IV", "Govindpuram Extension", "Loni", "Gyan Khand 3", "Sector 2 Vasundhara",
  "Tehri Garhwal", "Sanjay Nagar Sector 2", "Hanumangarh", "Karawal Nagar", "Noida Extension Sector 18", "Patel Nagar", "Vasundhara Sector 8", "Indirapuram Shakti Khand 3", "Maharashtra", "Karauli",
  "Chattarpur", "Gurdaspur", "Ghevra Metro", "Meerut", "Baksa", "Tarinkot", "Noida Sector 77", "Ri-Bhoi", "Noida Sector 153", "Behta Hazipur",
  "Vasundhara", "Dhaula Kuan", "Longleng", "Sector Phi 1", "Noida Sector 105", "Delhi Gate", "Govindpuram Sector 5", "Noida Sector 1", "Faridabad Sector 7", "Bokaro",
  "Palakkad", "Paschim Medinipur", "Noida Sector 64", "Barwani", "Chikkaballapur", "Pudukkottai", "Faridabad Sector 18", "West Bengal", "Anand Vihar ISBT", "Greater Noida Sector Pi 2",
  "Darshana", "ISBT Kashmere Gate", "East Champaran", "Noida Sector 119", "Jaypee Greens", "Chamoli", "Boudh", "Noida Sector 20", "Agartala", "Vadodara",
  "Fatehgarh Sahib", "Hailakandi", "Noida Sector 125", "Latur", "Noida Sector 3", "Greater Noida Sector Pi 1", "Nehrunagar Sector 2", "Vasundhara Sector 4", "Vidisha", "Deoghar",
  "Chatra", "Nashik", "Kaithal", "Indira Gandhi International Airport T3", "Techzone 1", "Kachchh", "Mahendragarh", "Dehradun", "Tronica City Sector B", "Kanker",
  "Noida Sector 63", "Sector Theta 1", "Mirzapur", "Hardoi", "Vijayawada", "Khowai", "Vinod Nagar Metro", "Rohtak", "Niti Khand 4", "Kota",
  "Dwarka Bus Depot", "Faridabad Sector 19", "Chirag Delhi", "Pathankot", "Kasna", "Mathura", "Nehrunagar Sector 1", "Noida Sector 91", "Galaxy North Avenue", "Reasi",
  "Parbhani", "Manipur", "Pratap Vihar Sector 3", "Koderma", "Noida Extension Sector 30", "North Delhi", "Palwal", "Raichur", "Jashpur", "Shahdol",
  "Pauri Garhwal", "Noida Sector 70", "Noida Sector 88", "Ramgarh", "Siddharth Vihar Sector 3", "Cuttack", "Paschim Vihar West", "Noida Sector 156", "Noida Sector 98", "Banda",
  "Ecotech 1", "Sector Mu 1", "Thane", "Chamba", "Mandya", "Noida Sector 150", "Rajendra Nagar Extension", "Khunti", "Govindpuri", "Indraprastha",
  "Bidar", "Gurugram Sector 15", "West Khasi Hills", "Hari Nagar", "Agra", "Moti Nagar Depot", "Nizamabad", "India Gate", "Kerala", "Noida Sector 109",
  "Narmada", "Raj Nagar Extension NH-58", "Joypurhat", "Crossings Republic Amrapali", "Azamgarh", "Pilibhit", "Pakur", "Bongaigaon", "Guna", "Ashok Nagar",
  "Vasundhara Enclave", "Hassan", "West Delhi", "Busselton", "Noida Sector 152", "Gumla", "Sector Omicron 3A", "Barpeta", "Indirapuram Nyay Khand 2", "Mau",
  "Harda", "Sangli", "Noida Sector 43", "Ecotech 3", "Greater Noida Sector Sigma 3", "Srinagar", "Faridabad Sector 4", "Shivamogga", "Jamia Nagar", "Lakshmi Nagar Metro",
  "Faridabad Sector 6", "Ludhiana", "Saharanpur", "Melbourne", "Crossing Republik", "Jind", "Kaushambi Metro", "Model Town", "Shajapur", "Wanaparthy",
  "Abhay Khand 1", "South Garo Hills", "Loni Bhopura", "Crossing Republik Panchsheel Wellington", "Nagaon", "Jhilmil Colony", "Kabul", "Buldhana", "Kandahar", "Kaimur",
  "Noida Sector 7", "Shastri Park", "Margao", "Peeragarhi", "Paschim Vihar", "Yamuna Vihar Depot", "Sirsa", "Vaishali Sector 8", "Kashmere Gate ISBT", "Noida Sector 69",
  "Punjabi Bagh", "Noida Sector 129", "Siddharth Vihar Sector 1", "Kannur", "Delhi", "Faridabad Sector 37", "Baba Colony", "Pitampura", "Indira Gandhi Indoor Stadium", "Gyan Khand 4",
  "Ghaziabad Bus Stand", "Raipur", "Noida Sector 75", "Dwarka Sector 10 Metro", "Samba", "Nanded", "Tonk", "Noida Sector 128", "Govindpuram Sector 4", "Basti",
  "Noida Sector 27", "Noida Sector 93A", "Noida Sector 25", "Noida Sector 95", "Lakhimpur Kheri", "Noida Sector 62", "Faridabad Sector 13", "Sri Potti Sriramulu Nellore", "Preet Vihar", "Jalna",
  "Khandwa", "Thoothukudi", "Bikaner", "Sanjay Nagar Sector 3", "Silchar", "Nand Nagri", "Kandhamal", "Kapurthala", "Trilokpuri Metro", "Gurugram Sector 41",
  "Gurugram Sector 44", "Sikar", "Bhiwani", "Gurugram Sector 8", "Punjab", "Dimapur", "Gurugram Sector 43", "Dundahera", "Balaghat", "Wayanad",
  "Noida Sector 106", "Surajpur", "Knowledge Park 5", "Imphal East", "Gurugram Sector 12", "Okhla Bird Sanctuary", "Lalitpur", "Sultanpur", "Garhwal (Pauri Garhwal)", "Vaishali",
  "Chittagong", "Rajnandgaon", "Kargil", "Noida Extension Sector 25", "New Friends Colony", "Noida Sector 56", "Greater Noida Sector Delta 1", "Noida Extension Sector 4", "Salem", "Paschim Vihar East",
  "Dwarka Sector 9", "Rampur", "Coimbatore", "Bijapur", "Sector 12 Vasundhara", "Gazipur", "Malviya Nagar", "Noida Sector 86", "Rohini Sector 13", "Wave City Harmony Floors",
  "Rohini Sector 3", "Rockhampton", "Kohima", "Sector 10 Vasundhara", "Vikarabad", "Greater Noida Sector Beta 1", "Burhanpur", "Muzaffarnagar", "Uttara Kannada", "Janakpuri",
  "Gurugram Sector 22", "Barakhamba Road", "Gurugram Sector 33", "Latehar", "Whyalla", "Lal Kuan", "Vaishali Sector 3", "Hauz Khas", "Knowledge Park 2", "Betul",
  "Dehradun", "Badarpur", "Dadra and Nagar Haveli and Daman and Diu", "Patiala", "Palam", "Pune", "Kurnool", "Lajpat Nagar Metro", "South 24 Parganas", "Noida Sector 87",
  "Wokha", "Uttarkashi", "Crossings Republic Supertech", "Shimla", "Sangrur", "Purba Bardhaman", "Nirman Vihar Metro", "Bishnupur", "Gurugram Sector 3", "Ganjam",
  "Sabzi Mandi", "Gurugram Sector 29", "Vaishali Extension", "West Siang", "Gurugram Sector 15 Part 2", "Nagaur", "Jangaon", "Shimla", "Siddharthnagar", "Jammu",
  "New Delhi Railway Station", "Dhalai", "Tirupattur", "Noida Sector 96", "Manesar", "Bijnor", "Sehore", "Ratlam", "Noida Sector 15A", "Lawngtlai",
  "Subhash Nagar", "Noida Sector 25A", "Surat", "Knowledge Park 1", "Kolhapur", "Bemetara", "Pathanamthitta", "Gurugram Sector 39", "Noida Sector 54", "Madurai",
  "Nangloi Metro", "Vaishali Sector 9", "Sector Mu 2", "Green Park", "Nainital", "Noida Sector 137", "Laxmi Nagar", "GTB Nagar", "Niti Khand 1", "Noida Sector 97",
  "Sector 11 Vasundhara", "Gandhinagar", "Kabirdham", "Shivpuri", "Vasant Vihar", "IP Extension", "Gurugram Sector 23A", "Noida Sector 116", "Saket Metro", "South Extension",
  "Muradnagar", "Pari Chowk", "Crossing Republik", "Pratap Vihar", "Noida Sector 99", "Govindpuram Sector 1", "Chandauli", "West Garo Hills", "Mayur Vihar Phase II", "Noida Sector 19",
  "Faridabad Sector 34", "Dwarka Sector 14", "Puducherry", "Chhattisgarh", "Welcome Colony", "Faridabad Sector 21", "Noida Sector 26", "Saket", "Sector Rho 2", "Medak",
  "Noida Sector 17", "Faridabad Sector 3", "Okhla Vihar", "Moti Bagh", "Noida Extension Sector 3", "Tikri Border", "Noida Sector 131", "North Goa", "Bhopura Extension", "Noida Sector 92",
  "Noida Sector 55", "Godda", "Amrapali Leisure Valley", "Bhilai", "Chamarajanagara", "Raigarh", "Saharsa", "Gurugram Sector 27", "Noida Extension Sector 1", "Telangana",
  "Sector Theta 2", "Karimnagar", "Noida Sector 121", "Kullu", "Sector Rho 1", "Jhalawar", "Ganganagar", "Bhubaneswar", "Noida Sector 35", "Noida Sector 103",
  "Chandigarh", "Noida Sector 115", "Noida Sector 83", "Mamit", "Ecotech 4", "Mayur Vihar Phase I", "Satna", "Hisar", "Noida", "Noida Sector 143",
  "Tikri Kalan", "Kirti Nagar", "Gurugram Sector 32", "Porbandar", "Chandigarh", "Kargil", "Changlang", "Raj Nagar Sector 4", "Khetlal", "Noida Sector 145",
  "Bijwasan", "East Jaintia Hills", "Qutub Minar", "Faridabad Sector 12", "Lunglei", "Farrukhabad", "Mansa", "Surat", "Janakpuri West Metro", "Baran",
  "ITO Metro", "Subhash Nagar Metro", "Dindigul", "NH-9 Ghaziabad", "Dasna Jail Area", "Patna", "Mehrauli", "Yamuna Expressway Sector 18", "Bhind", "Bhilwara",
  "Lucknow", "Noida Sector 143B", "Ernakulam", "Noida Sector 112", "Lohit", "Etawah", "Valsad", "Govindpuram Sector 6", "Mumbai Suburban", "Loni Border",
  "Govindpuram Sector 9", "Bandipora", "Faridabad Sector 30", "Itanagar", "Coimbatore", "Sector 6 Vasundhara", "Sagar", "Shastri Nagar Block C", "Noida Sector 157", "Faridabad Sector 25",
  "Mokokchung", "Noida Sector 44", "Najafgarh Metro", "Surya Nagar", "Noida Sector 89", "Balrampur", "Dharamshala", "Solapur", "Wave City Sector 2", "Dilshad Garden",
  "Chandrapur", "Noida Sector 9", "Lakhimpur", "Vasundhara Sector 10", "Sahibabad", "Nandurbar", "Gurugram Sector 1", "Sanjay Nagar Sector 4", "Kolkata", "Gurugram Sector 28",
  "Malda", "Rajiv Chowk", "Diu", "Noida Sector 93B", "Satyawati College", "Vasundhara Sector 3", "Ratnagiri", "Abupur", "Mysore", "Tumakuru",
  "Golaghat", "Sabarkantha", "Greater Noida Sector Gamma 2", "Himachal Pradesh", "Kokrajhar", "Jalore", "Lahaul and Spiti", "Niti Khand 2", "Tamil Nadu", "Sant Kabir Nagar",
  "Sundar Nagar", "Rajkot", "Shamli", "Noida Sector 107", "Dibang Valley", "Patel Chowk", "Yamuna Bank", "Noida Sector 50", "Techzone 2", "Greater Noida Sector Alpha 2",
  "Cachar", "Dhenkanal", "Katni", "Gaur City 2", "Shalimar Garden Ext 1", "Faridabad Bus Stand", "Vivek Vihar", "Gopalganj", "South Goa", "Subarnapur",
  "Gurugram Sector 23", "Gurugram Sector 21", "Bengaluru Urban", "Kulgam", "Virudhunagar", "Pithoragarh", "Anand Vihar Depot", "Badarpur Border", "Balangir", "Mohan Nagar",
  "Albany", "Rajgarh", "Siddharth Vihar", "Sector Chi 4", "Jalgaon", "Nalanda", "Kishanganj", "Assam", "Kondagaon", "Purnia",
  "Pune", "Badarpur Metro", "Noida Sector 151", "Rudraprayag", "Unnao", "Sector Chi 1", "Barnala", "Balkh", "Prakasam", "Kanshiram Nagar",
  "Faridabad Sector 21B", "Faridabad Sector 32", "Gurugram Sector 29", "Sonipat", "Gurugram Sector 18", "Mahagun Modern City", "Muzaffarpur", "Guwahati", "Noida Sector 102", "Mewat",
  "Noida Sector 138", "Visakhapatnam", "Noida Sector 16", "Panchmahal", "Gurugram Sector 36", "Noida Sector 22", "Sector 63 Indirapuram", "Ladakh", "Ramanathapuram", "Ukhrul",
  "Korba", "Zunheboto", "Dima Hasao", "Gurugram Sector 13", "West Jaintia Hills", "East Kameng", "Rohini East", "Noida Sector 113", "Faridabad Sector 5", "Nayagarh",
  "Bhadohi", "Aditya World City", "Muradabad", "Banswara", "Rajsamand", "Chennai", "Noida Sector 40", "Gaya", "Rajasthan", "Jagatsinghpur",
  "Dilshad Garden Metro", "Uttar Pradesh", "Noida Sector 78", "Dakshin Dinajpur", "Faridabad Sector 8", "Yamuna Expressway Sector 22", "Bhandara", "Palwal", "Dewas", "Tulsi Niketan",
  "Noida Sector 127", "Sector 3 Vasundhara", "Kavi Nagar Sector 14", "Dimapur", "Gaur City 1", "Noida Sector 68", "Gonda", "Noida Sector 66", "Mungeli", "Mayurbhanj",
  "Noida Sector 79", "Bundi", "Supaul", "Bharuch", "South Delhi", "Tughlakabad Metro", "Noida Sector 84", "Damoh", "Nagapattinam", "Raja Garden",
  "Indirapuram Vaibhav Khand", "Noida Extension Sector 17", "Haryana", "Noida Sector 19", "Ballia", "Nyay Khand 1", "Noida Sector 61", "Rohini West", "Jaintia Hills", "Wave City Dream Homes",
  "Noida Sector 132", "Faridabad Sector 9", "Sector Delta I Extension", "Ghazipur", "Sector Omicron 2A", "Mangolpuri", "West Singhbhum", "Lakhisarai", "Noida Sector 154", "Jhabua",
  "Vaishali Bus Depot", "Jamui", "Gurugram Sector 42", "Noida Sector 33", "Satara", "Nicobar", "Gurugram Sector 30", "Sector Chi 2", "Gurugram Sector 16", "Surajmal Vihar",
  "Sector 1 Vasundhara", "Noida Sector 58", "Nyay Khand 2", "Duhai Metro Station", "Kohima", "Abhay Khand 3", "Noida Sector 8", "Govindpuram Sector 3", "Patna", "Vellore",
  "Shopian"
];

export const toSlug = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
