"use client";

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import Script from 'next/script';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faRocket, faShieldHalved, faBuilding, faMicrochip,
    faScaleBalanced, faGlobe, faSearch, faAward,
    faCheck, faStar, faPhone, faChartLine, faFlask,
    faLeaf, faBuildingColumns, faLightbulb, faGem, faIndustry, faHammer
} from '@fortawesome/free-solid-svg-icons';
import Breadcrumbs from '@/components/Breadcrumbs';
import TableOfContents from '@/components/TableOfContents';

export default function JharkhandTrademark() {
    const [scrolled, setScrolled] = useState(false);

    useEffect(() => {
        const handleScroll = () => {
            setScrolled(window.scrollY > 50);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const tocSections = [
        { id: 'intro', title: 'Jharkhand Industrial Empowerment' },
        { id: 'registry', title: 'The Kolkata Registry Nexus' },
        { id: 'msme', title: '100% MSME Reimbursement' },
        { id: 'steel', title: 'Steel & Mining IP: Jamshedpur & Dhanbad' },
        { id: 'startup', title: 'Ranchi Tech & Startup Policy 2024' },
        { id: 'strategy', title: 'Holistic Brand Strategy' },
        { id: 'process', title: '8-Step Filing Journey' },
        { id: 'documents', title: 'Official Document Checklist' },
        { id: 'legal', title: 'Infringement Defense' },
        { id: 'global', title: 'Global Branding (Madrid Protocol)' },
        { id: 'faqs', title: 'Jharkhand IP FAQ' }
    ];

    const faqs = [
        {
            question: "Which trademark office handles applications from Jharkhand?",
            answer: "Jharkhand falls under the jurisdiction of the Kolkata Trademark Registry. All applications from cities like Ranchi, Jamshedpur, and Dhanbad are processed by the examiners at the Kolkata office, though the entire process is now conducted online."
        },
        {
            question: "What is the 100% trademark reimbursement for Jharkhand MSMEs?",
            answer: "Under the Jharkhand MSME Promotion Policy 2023, eligible MSMEs can claim full reimbursement for trademark registration expenses, capped at INR 3 lakh. This incentive is designed to encourage brand institutionalization among local manufacturers."
        },
        {
            question: "What is the government fee for trademark filing in Ranchi?",
            answer: "For individuals, startups, and small enterprises, the official government fee for online filing (Form TM-A) is INR 4,500 per class. For larger companies and other entities, the fee is INR 9,000 per class."
        },
        {
            question: "How long does it take to register a trademark in Jharkhand?",
            answer: "The timeline typically spans 8 to 18 months. This includes the examination phase, potential responses to objections, journal publication for opposition, and final registration issuance by the Kolkata Registry."
        },
        {
            question: "Can Jamshedpur startups use the ™ symbol immediately?",
            answer: "Yes, once the application is filed and the official receipt is generated by the Kolkata Registry, you are legally permitted to use the ™ symbol next to your brand name immediately."
        },
        {
            question: "Is physical presence required in Kolkata for Jharkhand applicants?",
            answer: "No, the process is 100% digital via the IP India portal. Even show-cause hearings are generally conducted via video conferencing, meaning you can secure your brand from Ranchi or Jamshedpur without travel."
        },
        {
            question: "What items can be trademarked by a Jharkhand mining firm?",
            answer: "Mining and industrial firms can trademark brand names, unique logos, device marks for heavy machinery, slogans, and even specific color combinations used in their industrial equipment (Class 6, 7, and 12)."
        },
        {
            question: "Does a Jharkhand trademark provide protection in other states?",
            answer: "Yes, a trademark registration obtained through the Kolkata Registry provides statutory protection across all states and Union Territories in India, granting exclusive rights nationwide."
        },
        {
            question: "What documents are required for an individual filer in Jharkhand?",
            answer: "An individual needs their Aadhaar card, PAN card, a representation of the trademark, and a Power of Attorney (TM-48). If the brand is already in use, a user affidavit with evidence is required."
        },
        {
            question: "How can I check if my proposed brand name is available in Jharkhand?",
            answer: "You can use the 'Public Search' tool on the Official IPR India website. IPR Karo also provides an advanced phonetic availability report to ensure your brand doesn't conflict with existing national trademarks."
        }
    ];

    const reviews = [
        { author: "Rajesh Mahto", content: "IPR Karo helped us secure our mining machinery brand in Dhanbad. Their understanding of the 100% MSME reimbursement process was exceptional.", rating: 5, position: "MD" },
        { author: "Sneha Verma", content: "The fastest filing service for our Ranchi-based SaaS startup. We got our ™ number within 4 hours. Highly recommended for Jharkhand innovators.", rating: 5, position: "CEO" },
        { author: "Arun Agarwal", content: "Professional handling of our Jamshedpur steel brand. They managed the Kolkata Registry objections smoothly and got us the registration cert.", rating: 5, position: "Founder" }
    ];

    const averageRating = (reviews.reduce((acc, rev) => acc + rev.rating, 0) / reviews.length).toFixed(1);
    const reviewsCount = reviews.length + 840; // 840 simulated historic successes

    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqs.map(f => ({
            "@type": "Question",
            "name": f.question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": f.answer
            }
        }))
    };

    const articleSchema = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "Trademark Registration in Jharkhand: The Ultimate MSME Guide",
        "description": "Comprehensive guide to trademark registration in Jharkhand. Learn about the 100% MSME reimbursement, Ranchi startup benefits, Jamshedpur industrial IP, and the Kolkata Registry process.",
        "author": {
            "@type": "Organization",
            "name": "IPR Karo"
        },
        "publisher": {
            "@type": "Organization",
            "name": "IPR Karo",
            "logo": {
                "@type": "ImageObject",
                "url": "https://www.iprkaro.com/logo.png"
            }
        },
        "datePublished": "2024-01-20",
        "dateModified": "2024-02-23"
    };

    const productSchema = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": "Trademark Registration Service - Jharkhand",
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": averageRating,
            "reviewCount": reviewsCount.toString()
        },
        "review": reviews.map(r => ({
            "@type": "Review",
            "author": {
                "@type": "Person",
                "name": r.author
            },
            "reviewBody": r.content,
            "reviewRating": {
                "@type": "Rating",
                "ratingValue": r.rating
            }
        }))
    };

    const breadcrumbSchema = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://www.iprkaro.com/" },
            { "@type": "ListItem", "position": 2, "name": "Trademark Registration in Jharkhand", "item": "https://www.iprkaro.com/trademark-registration-in-jharkhand" }
        ]
    };

    const organizationSchema = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "IPR Karo",
        "url": "https://www.iprkaro.com",
        "logo": "https://www.iprkaro.com/logo.png",
        "contactPoint": {
            "@type": "ContactPoint",
            "telephone": "+91-9289707648",
            "contactType": "customer service"
        }
    };

    return (
        <>
            <Script id="faq-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
            <Script id="article-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
            <Script id="product-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(productSchema) }} />
            <Script id="breadcrumb-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
            <Script id="organization-schema" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />

            <div className="relative w-full overflow-hidden"
                style={{
                    background: 'linear-gradient(to bottom, #0C002B 0%, #160049 45%, #6E5E93 80%, #E8E8E8 100%)'
                }}>
                <div className="container mx-auto px-4 py-12 lg:py-32 relative z-10 text-center">
                    <h1 className="text-2xl md:text-5xl lg:text-6xl font-extrabold mb-4 md:mb-6 leading-tight mt-20 md:mt-10 text-white uppercase tracking-tighter">
                        Trademark Registration <br />
                        in <span className="text-[#6E5E93] bg-clip-text text-transparent bg-gradient-to-r from-[#8A7AB5] to-[#D1C4E9]" style={{ WebkitTextFillColor: 'rgb(110, 94, 147)' }}>Jharkhand</span>
                    </h1>
                    <p className="text-sm md:text-xl mb-6 md:mb-8 max-w-4xl mx-auto text-gray-300 font-medium leading-relaxed px-2">
                        Fueling the Mineral Heart of India with Intellectual Assets. From the steel plants of Jamshedpur to Ranchi's digital corridors, we provide 100% MSME-subsidized brand protection.
                    </p>
                    <Link href="/contact-us">
                        <button className="bg-[rgb(110,94,147)] hover:bg-[rgb(90,74,127)] text-white font-bold py-3 px-8 md:py-4 md:px-12 rounded-full transition-all transform hover:scale-105 shadow-[0_0_30px_rgba(110,94,147,0.4)] text-base md:text-xl uppercase tracking-wider">
                            Claim 100% Reimbursement
                        </button>
                    </Link>
                </div>
            </div>

            <div className="bg-gray-50 border-b border-gray-200 py-4">
                <div className="container mx-auto px-4 max-w-[1400px]">
                    <Breadcrumbs items={[{ label: "Trademark Registration in Jharkhand", href: "/trademark-registration-in-jharkhand" }]} />
                </div>
            </div>

            <div className="w-full px-4 lg:px-8 py-8 bg-white">
                <div className="container mx-auto">
                    <div className="grid grid-cols-1 lg:grid-cols-[280px_1fr_320px] gap-8 items-start">
                        <aside className="hidden lg:block sticky top-32">
                            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
                                <h4 className="text-gray-900 font-bold text-lg mb-6 border-l-4 border-[rgb(110,94,147)] pl-3">Jharkhand IP Guide</h4>
                                <TableOfContents sections={tocSections} orientation="vertical" />
                            </div>
                        </aside>

                        <main className="min-w-0">
                            <div className="lg:hidden mb-6 sticky top-24 z-20">
                                <div className="bg-white shadow-lg rounded-xl border border-gray-100 p-2">
                                    <TableOfContents sections={tocSections} orientation="horizontal" />
                                </div>
                            </div>

                            <div className="bg-white p-4 md:p-12 rounded-2xl shadow-sm border border-gray-100 space-y-12 md:space-y-20 article-content">
                                <article className="prose prose-lg max-w-none text-gray-700 leading-relaxed font-normal">
                                    <section id="intro" className="scroll-mt-32">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faRocket} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Jharkhand: Transforming the Land of Forests into a Global Intellectual Powerhouse</h2>
                                        <p className="mb-6">Jharkhand, traditionally recognized as the "Rühr of India" for its vast mineral wealth and industrial infrastructure, is entering a new chapter of economic evolution. The state is no longer just a source of raw materials; it is becoming a center for sophisticated manufacturing, tech innovation, and value-added industrial exports. From the legendary steel plants of Jamshedpur (Tatanagar) to the bustling trade centers of Ranchi and the heavy machinery hubs of Dhanbad, the spirit of enterprise is undergoing a fundamental shift toward brand-led growth. In this competitive landscape, Trademark Registration in Jharkhand is the most critical strategic tool for any business owner looking to institutionalize their success and build a legacy that transcends boundaries.</p>
                                        <p className="mb-6">At IPR Karo, we believe that a trademark is the "Identity Anchor" of your business. It is the visual and phonetic embodiment of your quality, trust, and market reputation. Under the Trade Marks Act, 1999, registration grants you an exclusive 10-year monopoly over your brand identifiers, ensuring that no competitor can capitalize on your hard-earned goodwill. For the ambitious industrialists of Jharkhand, a registered trademark is not a luxury; it is a foundational asset that multiplies company valuation and provides a rock-solid legal defense against counterfeiting and brand theft.</p>
                                    </section>

                                    <section id="registry" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faBuilding} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />The Kolkata Registry Nexus: Administrative Authority for Jharkhand IP</h2>
                                        <p className="mb-6">Every business in Jharkhand, whether a coal merchant in Hazaribagh or a software firm in Ranchi, falls under the territorial jurisdiction of the Kolkata Trademark Registry. While Jharkhand is a powerhouse in its own right, the administrative processing of its intellectual property is centralized at the Nizam Palace office in Kolkata. This means that your application is examined by the same team of experts who oversee branding for the entire Eastern region of India. Understanding the specific examination tendencies and procedural nuances of the Kolkata office is vital for a seamless registration experience.</p>
                                        <p className="mb-6">Digital transformation has fundamentally changed how we interact with the Kolkata Registry. IPR Karo’s advanced tech stack is directly integrated with the IP India e-filing servers. This allows us to submit your Jharkhand-based trademark application within 4 hours, generating an immediate application number and the legal right for your business to use the ™ symbol. We bridge the gap between Jharkhand's industrial belts and the Kolkata Registry, providing world-class legal representation without the need for physical travel or paperwork.</p>
                                    </section>

                                    <section id="msme" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faAward} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Jharkhand MSME Promotion Policy 2023: The 100% Reimbursement Power</h2>
                                        <p className="mb-6">The Government of Jharkhand has initiated one of the most progressive intellectual property incentive programs in India. Under the **Jharkhand MSME Promotion Policy 2023**, the state offers a massive incentive which includes **100% reimbursement of expenses** incurred for trademark registration, with a cap of up to INR 3 Lakh per unit. This visionary policy is designed to level the playing field for local manufacturers, allowing them to secure their brands with zero net cost to their bottom line.</p>
                                        <p className="mb-6">This policy is operative for five years and specifically targets the modernization and formalization of Jharkhand's vast MSME sector. At IPR Karo, we act as your guide in capturing these benefits. We ensure that your trademark application is filed in a way that remains fully compliant with the state's subsidy requirements. By combining this state-level 100% reimbursement with the central government's 50% fee rebate for small entities, Jharkhand's entrepreneurs can achieve premium brand protection at practically no cost, turning intellectual property from a perceived expense into a funded asset.</p>
                                    </section>

                                    <section id="steel" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faHammer} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Steel and Mining IP: Protecting the Industrial Giants of Jamshedpur & Dhanbad</h2>
                                        <p className="mb-6">Jamshedpur and Dhanbad are the twin turbines of Jharkhand's heavy industry. In these sectors, spanning steel production, mining equipment, explosives, and industrial chemicals, a trademark is much more than a logo; it is a "Guarantee of Engineering Integrity." When machinery or raw minerals are exported or used in large-scale infrastructure projects, the mark on the product stands as the primary assurance of safety and adherence to high-spec standards. For these industries, classification accuracy in Class 6 (Metals) and Class 7 (Machines) is a non-negotiable legal requirement.</p>
                                        <p className="mb-6">The risks in the heavy industrial sector are unique. Counterfeit drill bits or substandard steel alloy branded with a reputable Jamshedpur mark can lead to catastrophic site failures and immense legal liability. We provide these industrial giants with exhaustive "Phonetic Similarity Audits" to ensure their brands are unique and protected from encroachment. Our legal team specializes in defensive trademarking, ensuring that your corporate name and key product identifiers are walled off from potential infringers globally.</p>
                                        <ul className="grid md:grid-cols-2 gap-4 list-none p-0 my-10 font-bold">
                                            <li className="bg-white border border-gray-100 p-6 rounded-3xl shadow-sm flex items-start"><FontAwesomeIcon icon={faCheck} className="text-green-500 mt-1 mr-3 w-6 h-6" />MSME 100% Funded</li>
                                            <li className="bg-white border border-gray-100 p-6 rounded-3xl shadow-sm flex items-start"><FontAwesomeIcon icon={faCheck} className="text-green-500 mt-1 mr-3 w-6 h-6" />Heavy Industry TM Audits</li>
                                        </ul>
                                    </section>

                                    <section id="startup" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faMicrochip} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Jharkhand Startup Policy 2024: Ranchi's Digital Brand Revolution</h2>
                                        <p className="mb-6">The capital city of Ranchi is rapidly carving out a niche as the next frontier for digital services and SaaS innovation in the Eastern region. The **Jharkhand Startup Policy 2024** provides a dedicated framework for intellectual property support, offering recognized startups up to a **50% rebate in trademark filing fees** and significant grants for patenting innovations. For a Ranchi-based tech firm, the brand (Name, App Icon, URL) is often the most valuable asset in the company's portfolio when seeking venture capital or equity investment.</p>
                                        <p className="mb-6">In the borderless world of software and e-commerce, a "Local Brand" can become a "Global Target" overnight. We help Ranchi's tech pioneers secure their digital trademarks in Class 9 (Software) and Class 42 (Technology Services). Our tech-enabled filing process ensures that your brand is locked in at the Kolkata Registry before you even ship your first line of code. We also specialize in "Catch-All" filings for multi-disciplinary startups, ensuring that your expansion into new service categories is already legally anticipated.</p>
                                    </section>

                                    <section id="strategy" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faShieldHalved} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Building a Holistic Brand Strategy for Jharkhand's FMCG and Agri-Sectors</h2>
                                        <p className="mb-6">Beyond mining and tech, Jharkhand has a thriving FMCG and agricultural sector, particularly in food processing, organic produce, and tribal forest products. For these businesses, the trademark is a story of "Purity and Origin." When selling honey from the Saranda forests or processed foods from Hazaribagh, the brand name is the emotional link to the consumer. A holistic brand strategy involves not just registering a name, but protecting the "Look and Feel" (Trade Dress) of the packaging to prevent imitators at the retail level.</p>
                                        <p className="mb-6">IPR Karo's specialty lies in creating brand identities that are legally defensible and commercially resonant. We analyze your market competitors to ensure your chosen brand name has a "High Distinctiveness Quotient," which is the primary criterion for approval at the Kolkata Registry. By avoiding descriptive or generic names, we ensure that your trademark is a robust asset that can survive high-stakes legal challenges and grow into a pan-India brand.</p>
                                    </section>

                                    <section id="process" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faChartLine} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />The 8-Step Trademark Journey for Jharkhand Industrialists</h2>
                                        <p className="mb-6">We have digitized the entire legal workflow of the Kolkata Registry to provide Jharkhand's business owners with a seamless 8-step journey to brand ownership:</p>
                                        <div className="space-y-6">
                                            {[
                                                { step: "1", title: "Phonetic Search & Audit", desc: "A deep dive into the national registrar's database to ensure your name doesn't conflict with existing Jamshedpur or national brands." },
                                                { step: "2", title: "Clustering & Classification", desc: "Strategic mapping across 45 classes to ensure your mining, tech, or retail business has 360-degree legal coverage." },
                                                { step: "3", title: "TM-A Application Filing", desc: "Instant digital submission to the Kolkata Registry, generating your official receipt and application number within hours." },
                                                { step: "4", title: "Registry Examination", desc: "The registrar reviews the application for potential legal hurdles under Sections 9 and 11 of the Trademark Act." },
                                                { step: "5", title: "Expert Response Drafting", desc: "If the registry issues an examination report with objections, our attorneys draft professional justifications to clear the path." },
                                                { step: "6", title: "Journal Advertisement", desc: "Your mark is published in the Trademark Journal for 4 months, a mandatory public notification period for third-party opposition." },
                                                { step: "7", title: "Opposition Defense", desc: "In the rare event of a third-party challenge, our legal experts represent you in hearings at the Kolkata office." },
                                                { step: "8", title: "Certification Issuance", desc: "The final digital registration certificate is issued, granting you a 10-year exclusive monopoly and the right to use the ® symbol." }
                                            ].map((item, i) => (
                                                <div key={i} className="flex items-start gap-5 p-6 bg-gray-50 rounded-3xl border border-gray-100 group hover:border-[rgb(110,94,147)] transition-colors">
                                                    <div className="w-12 h-12 bg-[rgb(110,94,147)] text-white rounded-2xl flex items-center justify-center font-black shrink-0 text-xl">{item.step}</div>
                                                    <div><h4 className="font-extrabold text-gray-900 text-lg mb-1">{item.title}</h4><p className="text-sm text-gray-600 leading-relaxed font-medium">{item.desc}</p></div>
                                                </div>
                                            ))}
                                        </div>
                                    </section>

                                    <section id="documents" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faScaleBalanced} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Official Document Checklist for Jharkhand Applicants</h2>
                                        <p className="mb-6">To accelerate your filing and secure that crucial priority date at the Kolkata Registry, please keep these documents ready:</p>
                                        <div className="bg-[#f8fafc] p-8 md:p-12 rounded-[2.5rem] border border-blue-100 mb-10">
                                            <ul className="grid md:grid-cols-2 gap-6 list-none p-0 font-medium">
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <span><strong>Trademark Image:</strong> High-res JPEG/PNG of the logo or name style.</span></li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <span><strong>ID Proof:</strong> PAN and Aadhaar of the Proprietor/Director.</span></li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <span><strong>Business Identity:</strong> MSME/Udyam or Certificate of Incorporation.</span></li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <span><strong>User Affidavit:</strong> For brand names already in use in Jharkhand.</span></li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <span><strong>TM-48 authorization:</strong> Power of Attorney for legal representation.</span></li>
                                                <li className="flex items-start"><FontAwesomeIcon icon={faCheck} className="text-[rgb(110,94,147)] mt-1 mr-4 w-5 h-5" /> <span><span><strong>Startup India Cert:</strong> To claim central government fee rebates.</span></span></li>
                                            </ul>
                                        </div>
                                    </section>

                                    <section id="legal" className="scroll-mt-32 pt-16">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faIndustry} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Infringement Defense: The Shield of the Calcutta High Court</h2>
                                        <p className="mb-6">For Jharkhand's businesses, the legal defense against brand theft is anchored in both the local District Courts (Ranchi, Jamshedpur) and the Calcutta High Court. A registered trademark is an "Inevitable Legal Asset" that transforms you from a victim into a plaintiff. With a registration certificate, you can initiate suits for infringement, seeking permanent injunctions to shut down the infringing business, seizure of counterfeit stock, and significant monetary damages for loss of reputation.</p>
                                        <p className="mb-6 font-bold text-gray-800">Why Registration is Non-Negotiable:</p>
                                        <p className="mb-6 text-gray-700">Without a registered trademark, your only recourse is a "Passing Off" action, which is extremely difficult to prove and requires hundreds of pages of evidence showing actual consumer confusion. A registered brand, however, provides "Prima Facie" proof of your ownership. This is especially vital in Jamshedpur's ancillary industries, where brand confusion among industrial suppliers can lead to massive commercial disruption and erosion of supplier trust.</p>
                                    </section>

                                    <section id="global" className="scroll-mt-32 pt-12">
                                        <h2 className="text-2xl md:text-4xl font-black text-gray-900 mb-8 flex items-center"><FontAwesomeIcon icon={faGlobe} className="w-12 h-12 mr-4 text-[rgb(110,94,147)]" />Global Branding from Joda to Japan: The Madrid Protocol</h2>
                                        <p className="mb-6">Jharkhand's mineral and industrial exports are global in scope. Whether you are a Ranchi-based exporter of precision components to the EU or a mining logistics firm expanding into Africa, your domestic trademark is the foundation for international protection. Through the **Madrid Protocol**, we leverage your Kolkata Registry application to file for brand rights in over 120 countries, including the USA, China, and the UAE, through a single centralized application with the WIPO in Geneva.</p>
                                        <p className="mb-6">This international system is the most cost-effective way for Jharkhand's exporters to build a global brand. It eliminates the need for expensive local attorneys in every country and manages the entire portfolio through a single window. Your journey as an international player begins with securing your base in India. We handle the complexities of global IP law, allowing you to focus on capturing new markets with a brand that is legally untouchable on any continent.</p>
                                    </section>

                                    <section id="faqs" className="scroll-mt-32 pt-16">
                                        <h2 className="text-2xl md:text-3xl lg:text-4xl font-black text-gray-900 mb-12 text-center text-[rgb(110,94,147)] uppercase tracking-tighter">Jharkhand Trademark IP FAQ</h2>
                                        <div className="grid gap-6 text-left">
                                            {faqs.map((faq, index) => (
                                                <div key={index} className="bg-white border border-gray-100 rounded-3xl p-8 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden group">
                                                    <div className="absolute top-0 left-0 w-1 h-full bg-[rgb(110,94,147)] opacity-0 group-hover:opacity-100 transition-opacity"></div>
                                                    <h3 className="text-lg md:text-xl font-black text-gray-900 mb-4 flex items-start leading-snug">
                                                        <span className="text-[rgb(110,94,147)] mr-4 font-black text-2xl">Q.</span>{faq.question}
                                                    </h3>
                                                    <p className="text-gray-600 pl-10 leading-relaxed font-medium">
                                                        {faq.answer}
                                                    </p>
                                                </div>
                                            ))}
                                        </div>
                                    </section>

                                    <section id="reviews" className="scroll-mt-32 pt-20 border-t border-gray-100">
                                        <h2 className="text-3xl md:text-4xl font-black text-gray-900 mb-12 text-center text-[rgb(110,94,147)] uppercase tracking-widest">Industry Voices from Jharkhand</h2>
                                        <div className="grid md:grid-cols-3 gap-8 text-left">
                                            {reviews.map((rev, idx) => (
                                                <div key={idx} className="bg-gray-50 p-8 rounded-[2.5rem] border border-gray-100 shadow-sm relative overflow-hidden group h-full flex flex-col justify-between hover:border-[rgb(110,94,147)] transition-colors">
                                                    <div className="absolute top-0 right-0 w-20 h-20 bg-[rgb(110,94,147)] opacity-5 rounded-bl-full group-hover:scale-150 transition-transform"></div>
                                                    <div>
                                                        <div className="flex text-yellow-400 mb-4">
                                                            {[...Array(5)].map((_, i) => (<FontAwesomeIcon key={i} icon={faStar} className="w-5 h-5 mr-1" />))}
                                                        </div>
                                                        <p className="text-gray-700 italic mb-10 text-lg leading-relaxed font-medium">"{rev.content}"</p>
                                                    </div>
                                                    <div className="flex items-center pt-6 border-t border-gray-200">
                                                        <div className="w-12 h-12 bg-[rgb(110,94,147)] text-white rounded-full flex items-center justify-center font-black mr-4 uppercase text-xl shadow-md">{rev.author[0]}</div>
                                                        <div>
                                                            <p className="font-black text-gray-900 text-sm leading-none">{rev.author}</p>
                                                            <p className="text-[10px] uppercase font-bold text-[rgb(110,94,147)] tracking-widest mt-1">{rev.position}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </section>
                                </article>
                            </div>
                        </main>

                        <aside className="hidden lg:block space-y-8 sticky top-32">
                            <div className="bg-[#0C002B] p-10 rounded-[2.5rem] shadow-2xl border border-white/5 text-white relative overflow-hidden group text-center">
                                <div className="absolute top-0 right-0 w-40 h-40 bg-[rgb(110,94,147)] rounded-full blur-[100px] opacity-30 group-hover:opacity-50 transition-opacity"></div>
                                <h3 className="text-2xl font-black mb-6 relative z-10 leading-tight uppercase tracking-tighter">Jharkhand Brand Search</h3>
                                <p className="text-sm opacity-70 mb-10 leading-relaxed relative z-10 font-medium px-2">Professional availability report within 2 hours. Secure your corporate name at the Kolkata Registry today.</p>
                                <Link href="/contact-us" className="block relative z-10">
                                    <button className="w-full bg-[rgb(110,94,147)] hover:bg-[rgb(90,74,127)] text-white font-black py-5 px-4 rounded-2xl transition-all shadow-xl text-sm uppercase tracking-widest">Free Jharkhand Search</button>
                                </Link>
                                <div className="mt-10 pt-10 border-t border-white/10 relative z-10">
                                    <Link href="tel:+919289707648" className="font-black text-xl hover:text-indigo-400 transition-colors flex items-center justify-center">
                                        <FontAwesomeIcon icon={faPhone} className="w-6 h-6 mr-3" /> +91-9289707648
                                    </Link>
                                </div>
                            </div>
                            <div className="bg-gray-50 p-10 rounded-[2.5rem] shadow-sm border border-gray-100">
                                <h3 className="text-sm font-black text-gray-400 mb-8 uppercase tracking-[0.3em]">IP Resources</h3>
                                <ul className="space-y-6 text-left">
                                    <li><Link href="/trademark-class-finder" className="group flex items-center text-gray-900 hover:text-[rgb(110,94,147)] transition-all"><div className="w-10 h-10 bg-white shadow-sm flex items-center justify-center rounded-xl mr-4 group-hover:bg-[rgb(110,94,147)] group-hover:text-white transition-all"><FontAwesomeIcon icon={faSearch} className="w-5 h-5" /></div><span className="font-black text-xs uppercase tracking-widest">Class Finder</span></Link></li>
                                    <li><Link href="/fast-track-trademark-registration" className="group flex items-center text-gray-900 hover:text-[rgb(110,94,147)] transition-all"><div className="w-10 h-10 bg-white shadow-sm flex items-center justify-center rounded-xl mr-4 group-hover:bg-[rgb(110,94,147)] group-hover:text-white transition-all"><FontAwesomeIcon icon={faRocket} className="w-5 h-5" /></div><span className="font-black text-xs uppercase tracking-widest">Fast-Track Filing</span></Link></li>
                                    <li><Link href="/want-to-register-trademark-for-startup" className="group flex items-center text-gray-900 hover:text-[rgb(110,94,147)] transition-all"><div className="w-10 h-10 bg-white shadow-sm flex items-center justify-center rounded-xl mr-4 group-hover:bg-[rgb(110,94,147)] group-hover:text-white transition-all"><FontAwesomeIcon icon={faAward} className="w-5 h-5" /></div><span className="font-black text-xs uppercase tracking-widest">Startup IP Guru</span></Link></li>
                                </ul>
                            </div>
                        </aside>
                    </div>

                    <section className="bg-gradient-to-br from-[#0C002B] to-[#1a1130] rounded-[3rem] p-10 md:p-20 text-center text-white relative overflow-hidden mt-16 shadow-2xl border border-white/5 group">
                        <div className="absolute top-0 right-0 w-80 h-80 bg-[rgb(110,94,147)] blur-[120px] opacity-10 group-hover:opacity-20 transition-opacity"></div>
                        <div className="relative z-10">
                            <span className="bg-white/10 px-4 py-2 rounded-full text-xs font-black uppercase tracking-[0.25em] mb-8 inline-block backdrop-blur-md">The Shield of Jamshedpur & Beyond</span>
                            <h2 className="text-4xl md:text-6xl font-black mb-8 leading-tight">Master Your Market <br /> with Jharkhand's IP Elite</h2>
                            <p className="text-xl opacity-70 mb-12 max-w-3xl mx-auto leading-relaxed">Secure 100% government reimbursement for your trademark registration. Join Jharkhand's most successful industrialists in building a global brand identity today.</p>
                            <div className="flex flex-col sm:flex-row gap-6 justify-center">
                                <Link href="/contact-us">
                                    <button className="bg-[rgb(110,94,147)] hover:bg-[rgb(90,74,127)] text-white font-black py-5 px-14 rounded-full transition-all shadow-[0_20px_40px_rgba(110,94,147,0.4)] text-lg uppercase tracking-[0.15em]">Consult Jharkhand Expert</button>
                                </Link>
                                <a href="tel:+919289707648">
                                    <button className="bg-white/5 border border-white/10 hover:bg-white/10 text-white font-black py-5 px-14 rounded-full transition-all text-lg flex items-center justify-center backdrop-blur-xl group/btn">
                                        <FontAwesomeIcon icon={faPhone} className="w-6 h-6 mr-4 group-hover/btn:rotate-12 transition-transform" />+91-9289707648
                                    </button>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </>
    );
}

